### ISSUE TITLE
This isn't an issue, its a suggestion.

### ISSUE THREAD

**Issue by ghost** [funkemunky/ACTutorial#2]
You could add a config.yml, because many Anticheats allow to enable and disable the checks. I've taken your code and added this, as well, as a reload command to reload the config.yml without the need of restarting the server. If you want to know how I did this, ask. Also, my reload command is a bit broken and sometimes it doesn't reload, could you also help me with this?

**Comment by ghost** [comment]
@funkemunky

**Comment by funkemunky** [comment]
I really only made this for tutorial purposes. You are 100% okay to fork this repository and add this yourself. It isn't too hard.

**Comment by ghost** [comment]
Well, I've just cloned the repo and added many more features. I've stopped working on this, because it got boring and there wasn't a point for me to do this. I'm just working on other plugins. Thanks for looking at my suggestion!
